apiVersion: v1
kind: Service
metadata:
  name: bread-sheet-server-svc
  namespace: default
spec:
  type: ClusterIP # Use LoadBalancer to expose externally via an ELB
  selector:
    app: bread-sheet-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000